namespace FFF.Migrations
{
	using FFF.Models;
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Migrations;
	using System.Linq;

	internal sealed class Configuration : DbMigrationsConfiguration<FFF.Models.DatabaseContext>
	{
		public Configuration()
		{
			AutomaticMigrationsEnabled = false;
			ContextKey = "FFF.Models.DatabaseContext";
		}

		protected override void Seed( FFF.Models.DatabaseContext context )
		{
			context.Genders.AddOrUpdate(
				s => s.Title,
				new Gender( "Male" ),
				new Gender( "Female" ) 
			);
			context.SaveChanges();

			context.CardTypes.AddOrUpdate(
				s => s.Title,
				new CardType("Visa"),
				new CardType("MasterCard"),
				new CardType("American Express"),
				new CardType("Discover")
			);
			context.SaveChanges();


			#region Seed States

			context.States.AddOrUpdate(
			s => s.Title,
			new State( "Alabama", "AL" ),
			new State( "Alaska", "AK" ),
			new State( "Arizona", "AZ" ),
			new State( "Arkansas", "AR" ),
			new State( "California", "CA" ),
			new State( "Colorado", "CO" ),
			new State( "Connecticut", "CT" ),
			new State( "Delaware", "DE" ),
			new State( "Florida", "FL" ),
			new State( "Georgia", "GA" ),
			new State( "Hawaii", "HI" ),
			new State( "Idaho", "ID" ),
			new State( "Illinois", "IL" ),
			new State( "Indiana", "IN" ),
			new State( "Iowa", "IA" ),
			new State( "Kansas", "KS" ),
			new State( "Kentucky", "KY" ),
			new State( "Louisiana", "LA" ),
			new State( "Maine", "ME" ),
			new State( "Maryland", "MD" ),
			new State( "Massachusetts", "MA" ),
			new State( "Michigan", "MI" ),
			new State( "Minnesota", "MN" ),
			new State( "Mississippi", "MS" ),
			new State( "Missouri", "MO" ),
			new State( "Montana", "MT" ),
			new State( "Nebraska", "NE" ),
			new State( "Nevada", "NV" ),
			new State( "New Hampshire", "NH" ),
			new State( "New Jersey", "NJ" ),
			new State( "New Mexico", "NM" ),
			new State( "New York", "NY" ),
			new State( "North Carolina", "NC" ),
			new State( "North Dakota", "ND" ),
			new State( "Ohio", "OH" ),
			new State( "Oklahoma", "OK" ),
			new State( "Oregon", "OR" ),
			new State( "Pennsylvania", "PA" ),
			new State( "Rhode Island", "RI" ),
			new State( "South Carolina", "SC" ),
			new State( "South Dakota", "SD" ),
			new State( "Tennessee", "TN" ),
			new State( "Texas", "TX" ),
			new State( "Utah", "UT" ),
			new State( "Vermont", "VT" ),
			new State( "Virginia", "VA" ),
			new State( "Washington", "WA" ),
			new State( "West Virginia", "WV" ),
			new State( "Wisconsin", "WI" ),
			new State( "Wyoming", "WY" )
			);
			#endregion
			context.SaveChanges();
			#region Seed TN Counties
			/*
			State Tennessee = context.Locations.OfType<State>().First( c => c.Title == "Tennessee" );
			context.Locations.AddOrUpdate
			(
				m => m.Title,
				new County("Anderson",Tennessee),
				new County("Bedford",Tennessee),
				new County("Benton",Tennessee),
				new County("Bledsoe",Tennessee),
				new County("Blount",Tennessee),
				new County("Bradley",Tennessee),
				new County("Campbell",Tennessee),
				new County("Cannon",Tennessee),
				new County("Carroll",Tennessee),
				new County("Carter",Tennessee),
				new County("Cheatham",Tennessee),
				new County("Chester",Tennessee),
				new County("Claiborne",Tennessee),
				new County("Cocke",Tennessee),
				new County("Coffee",Tennessee),
				new County("Crockett",Tennessee),
				new County("Cumberland",Tennessee),
				new County("Davidson",Tennessee),
				new County("Decatur",Tennessee),
				new County("DeKalb",Tennessee),
				new County("Dickson",Tennessee),
				new County("Dyer",Tennessee),
				new County("Fayette",Tennessee),
				new County("Fentress",Tennessee),
				new County("Franklin",Tennessee),
				new County("Gibson",Tennessee),
				new County("Giles",Tennessee),
				new County("Grainger",Tennessee),
				new County("Greene",Tennessee),
				new County("Grundy",Tennessee),
				new County("Hamblen",Tennessee),
				new County("Hamilton",Tennessee),
				new County("Hancock",Tennessee),
				new County("Hardeman",Tennessee),
				new County("Hardin",Tennessee),
				new County("Hawkins",Tennessee),
				new County("Haywood",Tennessee),
				new County("Henderson",Tennessee),
				new County("Henry",Tennessee),
				new County("Hickman",Tennessee),
				new County("Houston",Tennessee),
				new County("Humphreys",Tennessee),
				new County("Jackson",Tennessee),
				new County("Jefferson",Tennessee),
				new County("Johnson",Tennessee),
				new County("Knox",Tennessee),
				new County("Lake",Tennessee),
				new County("Lauderdale",Tennessee),
				new County("Lawrence",Tennessee),
				new County("Lewis",Tennessee),
				new County("Lincoln",Tennessee),
				new County("Loudon",Tennessee),
				new County("Macon",Tennessee),
				new County("Madison",Tennessee),
				new County("Marion",Tennessee),
				new County("Marshall",Tennessee),
				new County("Maury",Tennessee),
				new County("McMinn",Tennessee),
				new County("McNairy",Tennessee),
				new County("Meigs",Tennessee),
				new County("Monroe",Tennessee),
				new County("Montgomery",Tennessee),
				new County("Moore",Tennessee),
				new County("Morgan",Tennessee),
				new County("Obion",Tennessee),
				new County("Overton",Tennessee),
				new County("Perry",Tennessee),
				new County("Pickett",Tennessee),
				new County("Polk",Tennessee),
				new County("Putnam",Tennessee),
				new County("Rhea",Tennessee),
				new County("Roane",Tennessee),
				new County("Robertson",Tennessee),
				new County("Rutherford",Tennessee),
				new County("Scott",Tennessee),
				new County("Sequatchie",Tennessee),
				new County("Sevier",Tennessee),
				new County("Shelby",Tennessee),
				new County("Smith",Tennessee),
				new County("Stewart",Tennessee),
				new County("Sullivan",Tennessee),
				new County("Sumner",Tennessee),
				new County("Tipton",Tennessee),
				new County("Trousdale",Tennessee),
				new County("Unicoi",Tennessee),
				new County("Union",Tennessee),
				new County("VanBuren",Tennessee),
				new County("Warren",Tennessee),
				new County("Washington",Tennessee),
				new County("Wayne",Tennessee),
				new County("Weakley",Tennessee),
				new County("White",Tennessee),
				new County("Williamson",Tennessee),
				new County("Wilson",Tennessee)
			);
				*/
			#endregion
			context.SaveChanges();
			#region Seed TN Cities
			/*	State Tennessee = context.Locations.OfType<State>().First( c => c.Title == "Tennessee" );
			context.Locations.AddOrUpdate(
				m => m.Title,
				new City("Adams", Tennessee),
				new City("Adamsville", Tennessee),
				new City("Alamo", Tennessee),
				new City("Alcoa", Tennessee),
				new City("Alexandria", Tennessee),
				new City("Algood", Tennessee),
				new City("Allardt", Tennessee),
				new City("Altamont", Tennessee),
				new City("Ardmore", Tennessee),
				new City("Arlington", Tennessee),
				new City("Ashland City", Tennessee),
				new City("Athens", Tennessee),
				new City("Atoka", Tennessee),
				new City("Atwood", Tennessee),
				new City("Auburntown", Tennessee),
				new City("Baileyton", Tennessee),
				new City("Baneberry", Tennessee),
				new City("Bartlett", Tennessee),
				new City("Baxter", Tennessee),
				new City("Bean Station", Tennessee),
				new City("Beersheba Springs", Tennessee),
				new City("Bell Buckle", Tennessee),
				new City("Belle Meade", Tennessee),
				new City("Bells", Tennessee),
				new City("Benton", Tennessee),
				new City("Berry Hill", Tennessee),
				new City("Bethel Springs", Tennessee),
				new City("Big Sandy", Tennessee),
				new City("Blaine", Tennessee),
				new City("Bluff City", Tennessee),
				new City("Bolivar", Tennessee),
				new City("Braden", Tennessee),
				new City("Bradford", Tennessee),
				new City("Brentwood", Tennessee),
				new City("Brighton", Tennessee),
				new City("Bristol", Tennessee),
				new City("Brownsville", Tennessee),
				new City("Bruceton", Tennessee),
				new City("Bulls Gap", Tennessee),
				new City("Burlison", Tennessee),
				new City("Burns", Tennessee),
				new City("Byrdstown", Tennessee),
				new City("Calhoun", Tennessee),
				new City("Camden", Tennessee),
				new City("Carthage", Tennessee),
				new City("Caryville", Tennessee),
				new City("Cedar Hill", Tennessee),
				new City("Celina", Tennessee),
				new City("Centertown", Tennessee),
				new City("Centerville", Tennessee),
				new City("Chapel Hill", Tennessee),
				new City("Charleston", Tennessee),
				new City("Charlotte", Tennessee),
				new City("Chattanooga", Tennessee),
				new City("Church Hill", Tennessee),
				new City("Clarksburg", Tennessee),
				new City("Clarksville", Tennessee),
				new City("Cleveland", Tennessee),
				new City("Clifton", Tennessee),
				new City("Clinton", Tennessee),
				new City("Coalmont", Tennessee),
				new City("Collegedale", Tennessee),
				new City("Collierville", Tennessee),
				new City("Collinwood", Tennessee),
				new City("Columbia", Tennessee),
				new City("Cookeville", Tennessee),
				new City("Coopertown", Tennessee),
				new City("Copperhill", Tennessee),
				new City("Cornersville", Tennessee),
				new City("Cottage Grove", Tennessee),
				new City("Covington", Tennessee),
				new City("Cowan", Tennessee),
				new City("Crab Orchard", Tennessee),
				new City("Cross Plains", Tennessee),
				new City("Crossville", Tennessee),
				new City("Crump", Tennessee),
				new City("Cumberland City", Tennessee),
				new City("Cumberland Gap", Tennessee),
				new City("Dandridge", Tennessee),
				new City("Dayton", Tennessee),
				new City("Decatur", Tennessee),
				new City("Decaturville", Tennessee),
				new City("Decherd", Tennessee),
				new City("Dickson", Tennessee),
				new City("Dover", Tennessee),
				new City("Dowelltown", Tennessee),
				new City("Doyle", Tennessee),
				new City("Dresden", Tennessee),
				new City("Ducktown", Tennessee),
				new City("Dunlap", Tennessee),
				new City("Dyer", Tennessee),
				new City("Dyersburg", Tennessee),
				new City("Eagleville", Tennessee),
				new City("East Ridge", Tennessee),
				new City("Eastview", Tennessee),
				new City("Elizabethton", Tennessee),
				new City("Elkton", Tennessee),
				new City("Englewood", Tennessee),
				new City("Enville", Tennessee),
				new City("Erin", Tennessee),
				new City("Erwin", Tennessee),
				new City("Estill Springs", Tennessee),
				new City("Ethridge", Tennessee),
				new City("Etowah", Tennessee),
				new City("Fairview", Tennessee),
				new City("Farragut", Tennessee),
				new City("Fayetteville", Tennessee),
				new City("Finger", Tennessee),
				new City("Forest Hills", Tennessee),
				new City("Franklin", Tennessee),
				new City("Friendship", Tennessee),
				new City("Friendsville", Tennessee),
				new City("Gadsden", Tennessee),
				new City("Gainesboro", Tennessee),
				new City("Gallatin", Tennessee),
				new City("Gallaway", Tennessee),
				new City("Garland", Tennessee),
				new City("Gates", Tennessee),
				new City("Gatlinburg", Tennessee),
				new City("Germantown", Tennessee),
				new City("Gibson", Tennessee),
				new City("Gilt Edge", Tennessee),
				new City("Gleason", Tennessee),
				new City("Goodlettsville", Tennessee),
				new City("Gordonsville", Tennessee),
				new City("Grand Junction", Tennessee),
				new City("Graysville", Tennessee),
				new City("Greenback", Tennessee),
				new City("Greenbrier", Tennessee),
				new City("Greeneville", Tennessee),
				new City("Greenfield", Tennessee),
				new City("Gruetli-Laager", Tennessee),
				new City("Guys", Tennessee),
				new City("Halls", Tennessee),
				new City("Harriman", Tennessee),
				new City("Harrogate", Tennessee),
				new City("Hartsville", Tennessee),
				new City("Helenwood", Tennessee),
				new City("Henderson", Tennessee),
				new City("Hendersonville", Tennessee),
				new City("Henning", Tennessee),
				new City("Henry", Tennessee),
				new City("Hickory Valley", Tennessee),
				new City("Hickory Withe", Tennessee),
				new City("Hohenwald", Tennessee),
				new City("Hollow Rock", Tennessee),
				new City("Hornbeak", Tennessee),
				new City("Hornsby", Tennessee),
				new City("Humboldt", Tennessee),
				new City("Huntingdon", Tennessee),
				new City("Huntland", Tennessee),
				new City("Huntsville", Tennessee),
				new City("Iron City", Tennessee),
				new City("Jacksboro", Tennessee),
				new City("Jackson", Tennessee),
				new City("Jamestown", Tennessee),
				new City("Jasper", Tennessee),
				new City("Jefferson City", Tennessee),
				new City("Jellico", Tennessee),
				new City("Johnson City", Tennessee),
				new City("Jonesborough", Tennessee),
				new City("Kenton", Tennessee),
				new City("Kimball", Tennessee),
				new City("Kingsport", Tennessee),
				new City("Kingston", Tennessee),
				new City("Kingston Springs", Tennessee),
				new City("Knoxville", Tennessee),
				new City("La Follette", Tennessee),
				new City("La Vergne", Tennessee),
				new City("Lafayette", Tennessee),
				new City("LaGrange", Tennessee),
				new City("Lake City", Tennessee),
				new City("Lakeland", Tennessee),
				new City("Lakesite", Tennessee),
				new City("Lakewood", Tennessee),
				new City("Lawrenceburg", Tennessee),
				new City("Lebanon", Tennessee),
				new City("Lenoir City", Tennessee),
				new City("Lewisburg", Tennessee),
				new City("Lexington", Tennessee),
				new City("Liberty", Tennessee),
				new City("Linden", Tennessee),
				new City("Livingston", Tennessee),
				new City("Lobelville", Tennessee),
				new City("Lookout Mountain", Tennessee),
				new City("Loretto", Tennessee),
				new City("Loudon", Tennessee),
				new City("Louisville", Tennessee),
				new City("Luttrell", Tennessee),
				new City("Lynchburg", Tennessee),
				new City("Lynnville", Tennessee),
				new City("Madisonville", Tennessee),
				new City("Manchester", Tennessee),
				new City("Martin", Tennessee),
				new City("Maryville", Tennessee),
				new City("Mason", Tennessee),
				new City("Maury City", Tennessee),
				new City("Maynardville", Tennessee),
				new City("McEwen", Tennessee),
				new City("McKenzie", Tennessee),
				new City("McLemoresville", Tennessee),
				new City("McMinnville", Tennessee),
				new City("Medina", Tennessee),
				new City("Medon", Tennessee),
				new City("Memphis", Tennessee),
				new City("Michie", Tennessee),
				new City("Middleton", Tennessee),
				new City("Midtown", Tennessee),
				new City("Milan", Tennessee),
				new City("Milledgeville", Tennessee),
				new City("Millersville", Tennessee),
				new City("Millington", Tennessee),
				new City("Minor Hill", Tennessee),
				new City("Mitchellville", Tennessee),
				new City("Monteagle", Tennessee),
				new City("Monterey", Tennessee),
				new City("Morrison", Tennessee),
				new City("Morristown", Tennessee),
				new City("Moscow", Tennessee),
				new City("Mosheim", Tennessee),
				new City("Mount Carmel", Tennessee),
				new City("Mount Juliet", Tennessee),
				new City("Mount Pleasant", Tennessee),
				new City("Mountain City", Tennessee),
				new City("Munford", Tennessee),
				new City("Murfreesboro", Tennessee),
				new City("Nashville", Tennessee),
				new City("New Hope", Tennessee),
				new City("New Johnsonville", Tennessee),
				new City("New Market", Tennessee),
				new City("New Tazewell", Tennessee),
				new City("Newbern", Tennessee),
				new City("Newport", Tennessee),
				new City("Niota", Tennessee),
				new City("Nolensville", Tennessee),
				new City("Normandy", Tennessee),
				new City("Norris", Tennessee),
				new City("Oak Hill", Tennessee),
				new City("Oak Ridge", Tennessee),
				new City("Oakdale", Tennessee),
				new City("Oakland", Tennessee),
				new City("Obion", Tennessee),
				new City("Oliver Springs", Tennessee),
				new City("Oneida", Tennessee),
				new City("Orlinda", Tennessee),
				new City("Orme", Tennessee),
				new City("Palmer", Tennessee),
				new City("Paris", Tennessee),
				new City("Parker's Crossroads", Tennessee),
				new City("Parrottsville", Tennessee),
				new City("Parsons", Tennessee),
				new City("Pegram", Tennessee),
				new City("Petersburg", Tennessee),
				new City("Philadelphia", Tennessee),
				new City("Pigeon Forge", Tennessee),
				new City("Pikeville", Tennessee),
				new City("Piperton", Tennessee),
				new City("Pittman Center", Tennessee),
				new City("Plainview", Tennessee),
				new City("Pleasant Hill", Tennessee),
				new City("Pleasant View", Tennessee),
				new City("Portland", Tennessee),
				new City("Powell's Crossroads", Tennessee),
				new City("Pulaski", Tennessee),
				new City("Puryear", Tennessee),
				new City("Ramer", Tennessee),
				new City("Red Bank", Tennessee),
				new City("Red Boiling Springs", Tennessee),
				new City("Ridgely", Tennessee),
				new City("Ridgeside", Tennessee),
				new City("Ridgetop", Tennessee),
				new City("Ripley", Tennessee),
				new City("Rives", Tennessee),
				new City("Rockford", Tennessee),
				new City("Rockwood", Tennessee),
				new City("Rogersville", Tennessee),
				new City("Rossville", Tennessee),
				new City("Rutherford", Tennessee),
				new City("Rutledge", Tennessee),
				new City("Saltillo", Tennessee),
				new City("Samburg", Tennessee),
				new City("Sardis", Tennessee),
				new City("Saulsbury", Tennessee),
				new City("Savannah", Tennessee),
				new City("Scotts Hill", Tennessee),
				new City("Selmer", Tennessee),
				new City("Sevierville", Tennessee),
				new City("Sharon", Tennessee),
				new City("Shelbyville", Tennessee),
				new City("Signal Mountain", Tennessee),
				new City("Silerton", Tennessee),
				new City("Slayden", Tennessee),
				new City("Smithville", Tennessee),
				new City("Smyrna", Tennessee),
				new City("Sneedville", Tennessee),
				new City("Soddy-Daisy", Tennessee),
				new City("Somerville", Tennessee),
				new City("South Carthage", Tennessee),
				new City("South Fulton", Tennessee),
				new City("South Pittsburg", Tennessee),
				new City("Sparta", Tennessee),
				new City("Spencer", Tennessee),
				new City("Spring City", Tennessee),
				new City("Spring Hill", Tennessee),
				new City("Springfield", Tennessee),
				new City("St. Joseph", Tennessee),
				new City("Stanton", Tennessee),
				new City("Stantonville", Tennessee),
				new City("Sunbright", Tennessee),
				new City("Surgoinsville", Tennessee),
				new City("Sweetwater", Tennessee),
				new City("Tazewell", Tennessee),
				new City("Tellico Plains", Tennessee),
				new City("Tennessee Ridge", Tennessee),
				new City("Thompson's Station", Tennessee),
				new City("Three Way", Tennessee),
				new City("Tiptonville", Tennessee),
				new City("Toone", Tennessee),
				new City("Townsend", Tennessee),
				new City("Tracy City", Tennessee),
				new City("Trenton", Tennessee),
				new City("Trezevant", Tennessee),
				new City("Trimble", Tennessee),
				new City("Troy", Tennessee),
				new City("Tullahoma", Tennessee),
				new City("Tusculum", Tennessee),
				new City("Unicoi", Tennessee),
				new City("Union City", Tennessee),
				new City("Vanleer", Tennessee),
				new City("Viola", Tennessee),
				new City("Vonore", Tennessee),
				new City("Walden", Tennessee),
				new City("Walnut Grove", Tennessee),
				new City("Wartburg", Tennessee),
				new City("Wartrace", Tennessee),
				new City("Watauga", Tennessee),
				new City("Watertown", Tennessee),
				new City("Waverly", Tennessee),
				new City("Waynesboro", Tennessee),
				new City("Westmoreland", Tennessee),
				new City("White Bluff", Tennessee),
				new City("White House", Tennessee),
				new City("White Pine", Tennessee),
				new City("Whiteville", Tennessee),
				new City("Whitwell", Tennessee),
				new City("Williston", Tennessee),
				new City("Winchester", Tennessee),
				new City("Winfield", Tennessee),
				new City("Woodbury", Tennessee),
				new City("Woodland Mills", Tennessee),
				new City("Yorkville", Tennessee)
			);*/
			#endregion
			context.SaveChanges();
			#region Seed Chattanooga Chains (available on chattanoogafun.com)

			context.Chains.AddOrUpdate
			(
				c => c.Title,
				new Chain( "1885 Grill" ),
				new Chain( "212 Market Restaurant" ),
				new Chain( "3rd Deck Burger Bar" ),
				new Chain( "A Tennessee Guest Ranch" ),
				new Chain( "Abuelo's" ),
				new Chain( "Acropolis" ),
				new Chain( "Alleia" ),
				new Chain( "Amigo Mexican Restaurant" ),
				new Chain( "Aquarium Foods" ),
				new Chain( "Asia Buffet" ),
				new Chain( "Back Inn Café" ),
				new Chain( "Bar Louie" ),
				new Chain( "Barnsley Gardens Resort" ),
				new Chain( "Bea's Restaurant" ),
				new Chain( "Ben & Jerry's" ),
				new Chain( "Big River Grille & Brewing Works" ),
				new Chain( "Big Rock Grill" ),
				new Chain( "Bistro" ),
				new Chain( "Blacksmith's Gastro Pub" ),
				new Chain( "Blue Orleans Seafood Restaurant" ),
				new Chain( "Blue Plate" ),
				new Chain( "Bluewater Grille" ),
				new Chain( "Bluff View Art District" ),
				new Chain( "Bluff View Bakery" ),
				new Chain( "Boathouse Rotisserie & Raw Bar" ),
				new Chain( "Bojangle's" ),
				new Chain( "Bonefish Grill" ),
				new Chain( "Brass Hat Bar & Grill" ),
				new Chain( "Brewhaus Restaurant" ),
				new Chain( "Brix Nouvenau, Wine & Cheese Bar" ),
				new Chain( "Broad Street Grille" ),
				new Chain( "Bud's Sports Bar" ),
				new Chain( "Buffalo Wild Wings" ),
				new Chain( "Buttonwillow Civil War Dinner Teater" ),
				new Chain( "Café 7" ),
				new Chain( "Canyon Grill" ),
				new Chain( "Carabba's Italian Grill" ),
				new Chain( "Cavern Café" ),
				new Chain( "Champy's Chicken" ),
				new Chain( "Chattanooga Billiard Club" ),
				new Chain( "Chattanooga Choo Choo" ),
				new Chain( "Chattanooga's Julie Darling Donuts" ),
				new Chain( "Cheeburger Cheeburger" ),
				new Chain( "Chef Lin" ),
				new Chain( "Cherry Street Diner" ),
				new Chain( "Chick-fil-a" ),
				new Chain( "Chili's" ),
				new Chain( "Choo Choo Café Espresso" ),
				new Chain( "CiCi's Pizza" ),
				new Chain( "City Café Diner" ),
				new Chain( "Cold Stone Creamery" ),
				new Chain( "Comedy Catch and Giggles Grill" ),
				new Chain( "Community Pie" ),
				new Chain( "Cracker Barrel" ),
				new Chain( "Crave Café & Bakery" ),
				new Chain( "Cupcake Kitchen" ),
				new Chain( "DeBarge Vineyards and Winery" ),
				new Chain( "Dipped Fresh" ),
				new Chain( "Easy Bistro & Bar" ),
				new Chain( "Eats Food Tours" ),
				new Chain( "El Meson Mexican Restaurant" ),
				new Chain( "Electric Coway" ),
				new Chain( "Elemental" ),
				new Chain( "ELEVENT/H20 Bar" ),
				new Chain( "Famous Dave's" ),
				new Chain( "Five Guys Burgers and Fries" ),
				new Chain( "FoodWorks" ),
				new Chain( "Fork and Pie" ),
				new Chain( "Fox & Hound Pub & Grille" ),
				new Chain( "Fresh To Order" ),
				new Chain( "Fuji Steak & Sushi" ),
				new Chain( "Fun Forest Foods" ),
				new Chain( "Fuse" ),
				new Chain( "Genghis Grill" ),
				new Chain( "George Dickel Distillery" ),
				new Chain( "Georgia Winery" ),
				new Chain( "GiGi's Cupcakes" ),
				new Chain( "Go Bagel" ),
				new Chain( "GOOD Dog Restaurant, Inc." ),
				new Chain( "Grandview" ),
				new Chain( "Green Thumb Vegetarian Kitchen" ),
				new Chain( "Greyfriar's Coffee & Tea Co." ),
				new Chain( "Hair of the Dog Pub" ),
				new Chain( "Hardee's" ),
				new Chain( "Hennen's" ),
				new Chain( "Herman's Soulfood" ),
				new Chain( "Hill City Pizza" ),
				new Chain( "Hixson Pike Diner" ),
				new Chain( "Hooters" ),
				new Chain( "IHOP" ),
				new Chain( "Include Concessions" ),
				new Chain( "J. Alexander's" ),
				new Chain( "Jack Daniel Distillery" ),
				new Chain( "Jason's Deli" ),
				new Chain( "JC's Family BBQ" ),
				new Chain( "Jefferson's" ),
				new Chain( "Jenkins Country Style Buffet" ),
				new Chain( "Jim Oliver's Smoke House Restaurant" ),
				new Chain( "Jimmy John's" ),
				new Chain( "Kanpai Tokyo" ),
				new Chain( "Kicks Lounge" ),
				new Chain( "Krystal" ),
				new Chain( "La Altena Diner" ),
				new Chain( "Little Billy's BBQ" ),
				new Chain( "Local 191" ),
				new Chain( "Logan's Roadhouse" ),
				new Chain( "Long Branch Lakes Café" ),
				new Chain( "Longhorn Restaurant" ),
				new Chain( "Longhorn Steakhouse" ),
				new Chain( "Lookout Café's" ),
				new Chain( "Lupi's Pizza Pies" ),
				new Chain( "Marco's Italian Bistro" ),
				new Chain( "McDonalds" ),
				new Chain( "Mean Mug Coffeehouse" ),
				new Chain( "Meeting Place" ),
				new Chain( "Mellow Mushroom" ),
				new Chain( "Memo Grill" ),
				new Chain( "Milk and Honey" ),
				new Chain( "Mindy B's Deli" ),
				new Chain( "MOCHO Restaurant & Music Lounge" ),
				new Chain( "Moe's Southwest Grill" ),
				new Chain( "Mom's Italian Villa" ),
				new Chain( "Mr. T's Pizza and Ice Cream" ),
				new Chain( "Mt. Vernon Restaurant" ),
				new Chain( "New China Buffet & Grill" ),
				new Chain( "New York Pizza Department" ),
				new Chain( "Niedlov's Breakworks" ),
				new Chain( "Nikki's Drive Inn" ),
				new Chain( "Noodles and Company" ),
				new Chain( "North Shore Lunch" ),
				new Chain( "Northshore Grille" ),
				new Chain( "Olive Chattanooga" ),
				new Chain( "Olive Garden" ),
				new Chain( "P.F. Chang's" ),
				new Chain( "Panera Bread" ),
				new Chain( "Papa John's Pizza" ),
				new Chain( "Piccadilly Cafeteria, Inc." ),
				new Chain( "Pickle Barrel" ),
				new Chain( "Poblanos Mexican Cuisine" ),
				new Chain( "Porter's Steakhouse" ),
				new Chain( "Provino's Italian" ),
				new Chain( "Public House" ),
				new Chain( "Rafael's Pizzeria" ),
				new Chain( "RAW Nightclub & Sushi Bar" ),
				new Chain( "Red Lobster" ),
				new Chain( "Red Robin Gourmet Burgers" ),
				new Chain( "Rembrandt's Coffe House" ),
				new Chain( "Rhythm & Brews" ),
				new Chain( "Rib & Loin" ),
				new Chain( "Rita's Ice Custard" ),
				new Chain( "River Street Deli" ),
				new Chain( "Riverside Catfish House" ),
				new Chain( "Ruth's Chris Steak House" ),
				new Chain( "Sekisui Chattanooga" ),
				new Chain( "Shoney's" ),
				new Chain( "Shuford's BBQ" ),
				new Chain( "Silver Diner" ),
				new Chain( "Sing It or Wing It" ),
				new Chain( "Sitar Indian Cuisine" ),
				new Chain( "Southern Belle Riverboat" ),
				new Chain( "Souther Burger" ),
				new Chain( "Southern Star" ),
				new Chain( "Southside Saloon & Bistro" ),
				new Chain( "Splitz Bar & Grill/Pin Strikes" ),
				new Chain( "St. Elmo Deli & Grill" ),
				new Chain( "St. John's Restaurant" ),
				new Chain( "Starbucks" ),
				new Chain( "Station House Restaurant" ),
				new Chain( "Sticky Fingers" ),
				new Chain( "Subway" ),
				new Chain( "Sugar's Ribs" ),
				new Chain( "Sugary Creations" ),
				new Chain( "Sushi Nabe" ),
				new Chain( "Sweet Pepper's Deli" ),
				new Chain( "Sweet Stop Ice Cream & Candy Shoppe" ),
				new Chain( "Taco Mac" ),
				new Chain( "Taco Mamacita" ),
				new Chain( "Tasty Daylight Donuts" ),
				new Chain( "Tazikis Mediterranean Café" ),
				new Chain( "T-Bones Sports Café" ),
				new Chain( "Tennessee Moonshine Cakes" ),
				new Chain( "terraMae Appalachian Bistro" ),
				new Chain( "TGI Friday's, Inc." ),
				new Chain( "Thai Smile" ),
				new Chain( "The Big Table" ),
				new Chain( "The Camp House" ),
				new Chain( "The Chop House" ),
				new Chain( "The English Rose" ),
				new Chain( "The Epicurean Restaurant" ),
				new Chain( "The Foundry" ),
				new Chain( "The Front Porch" ),
				new Chain( "The Gardens" ),
				new Chain( "The Honest Pint" ),
				new Chain( "The Ice Cream Show" ),
				new Chain( "The Palms" ),
				new Chain( "The Terminal Brewhouse" ),
				new Chain( "The Terrace Grille" ),
				new Chain( "The Yellow Deli" ),
				new Chain( "Tony's Pasta Shop & Trattoria" ),
				new Chain( "Urban Stack Burger Lounge" ),
				new Chain( "Vaudeville Café" ),
				new Chain( "Wendy's" )
			);
			#endregion
			context.SaveChanges();
			#region Carriers
			context.Carriers.AddOrUpdate
			(
				c => c.Title,
				new Carrier( "Verizon", "@vtext.com" )
			);
			#endregion
			context.SaveChanges();
			#region Seed Restaurants around Chattanooga
			/*			Chain McDonalds = context.Chains.First(c => c.Title == "McDonalds");
			context.Addresses.AddOrUpdate
			(
				c => c.Nick,
				new Address("Campus", "1117 E 3rd St", null, "Chattanooga", context.States.First(c => c.Title == "Tennessee"), "37403")
			);
			context.SaveChanges();
			
			context.Restaurants.AddOrUpdate
			(
				c => c.Address,
				new Restaurant(McDonalds, new Phone(context.Carriers.First(c => c.Title == "Verizon"),"423", "267", "1188"), context.Addresses.First(c => c.Nick == "Campus"))
				new Restaurant(McDonalds, new Phone("423", "698", "8400")),
				new Restaurant(McDonalds, new Phone("423", "870", "8400")),
				new Restaurant(McDonalds, new Phone("423", "867", "2345")),
				new Restaurant(McDonalds, new Phone("423", "821", "7976"))
			);*/
			#endregion
			context.SaveChanges();
			#region Seed Menus
			Chain McDonalds = context.Chains.First( c => c.Title == "McDonalds" );
			
			Category menu = new Category("Menus");
			context.Categories.AddOrUpdate
			(
				c => c.Title,
				menu,
				new Category( "Burgers & Sandwiches", menu ),
				new Category( "Chicken & Fish", menu ),
				new Category( "Breakfast", menu ),
				new Category( "Salads", menu ),
				new Category( "Snack & Sides", menu ),
				new Category( "McCafé", menu ),
				new Category( "Beverages", menu ),
				new Category( "Desserts & Shakes", menu )
			);
			#endregion
			context.SaveChanges();
			#region Seed Items
			context.Items.AddOrUpdate
			(
				c => c.Title,
				new Food( McDonalds, "Big Mac", "" ),
				new Food( McDonalds, "Cheeseburger", "" ),
				new Food( McDonalds, "ChipotleBBQSnackWrap(Crispy)", "" ),
				new Food( McDonalds, "ChipotleBBQSnackWrap(Grilled)", "" ),
				new Food( McDonalds, "DailyDouble", "" ),
				new Food( McDonalds, "DoubleCheeseburger", "" ),
				new Food( McDonalds, "DoubleQuarterPounderwithCheese", "" ),
				new Food( McDonalds, "Filet-O-Fish", "" ),
				new Food( McDonalds, "GrilledOnionCheddar", "" ),
				new Food( McDonalds, "Hamburger", "" ),
				new Food( McDonalds, "HoneyMustardSnackWrap(Crispy)", "" ),
				new Food( McDonalds, "HoneyMustardSnackWrap(Grilled)", "" ),
				new Food( McDonalds, "MacSnackWrap", "" ),
				new Food( McDonalds, "McChicken®", "" ),
				new Food( McDonalds, "McDouble", "" ),
				new Food( McDonalds, "McRib®", "" ),
				new Food( McDonalds, "PremiumCrispyChickenClassicSandwich", "" ),
				new Food( McDonalds, "PremiumCrispyChickenClubSandwich", "" ),
				new Food( McDonalds, "PremiumCrispyChickenRanchBLTSandwich", "" ),
				new Food( McDonalds, "PremiumGrilledChickenClassicSandwich", "" ),
				new Food( McDonalds, "PremiumGrilledChickenClubSandwich", "" ),
				new Food( McDonalds, "PremiumGrilledChickenRanchBLTSandwich", "" ),
				new Food( McDonalds, "PremiumMcWrapChicken&Bacon(Crispy)", "" ),
				new Food( McDonalds, "PremiumMcWrapChicken&Bacon(Grilled)", "" ),
				new Food( McDonalds, "PremiumMcWrapChicken&Ranch(Crispy)", "" ),
				new Food( McDonalds, "PremiumMcWrapChicken&Ranch(Grilled)", "" ),
				new Food( McDonalds, "PremiumMcWrapChickenSweetChili(Crispy)", "" ),
				new Food( McDonalds, "PremiumMcWrapChickenSweetChili(Grilled)", "" ),
				new Food( McDonalds, "QuarterPounderBacon&Cheese", "" ),
				new Food( McDonalds, "QuarterPounderBaconHabaneroRanch", "" ),
				new Food( McDonalds, "QuarterPounderBLT", "" ),
				new Food( McDonalds, "QuarterPounderDeluxe", "" ),
				new Food( McDonalds, "QuarterPounder®withCheese", "" ),
				new Food( McDonalds, "RanchSnackWrap®(Crispy)", "" ),
				new Food( McDonalds, "RanchSnackWrap®(Grilled)", "" ),
				new Food( McDonalds, "SouthernStyleCrispyChickenSandwich", "" )
			);
			#endregion
			context.SaveChanges();
		}
	}
}
